server:
  port: 80
  servlet:
    context-path: /api
logging:
  level:
    web: info
spring:
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/motto?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: sabercon
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 开发时可以设置为更新，每次启动会更新数据库
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    database: 0 # Redis数据库索引（默认为0）
    password: # Redis服务器连接密码（默认为空）
aliyun:
  # OSS相关配置信息
  oss:
    accessKeyId: LTAIFCfcNOj1amZh # 访问身份验证中用到用户标识
    accessKeySecret: YLXDCGqwn2GzzrQBjIcTRg1gIWDIk9 # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    bucketName: motto # oss的存储空间
    maxSize: 100 # 上传文件大小(M)
    dir:
      avatar: user/avatar/
      diary-img: diary/img/
      pic: resource/pic/
      file: resource/file/
  # 阿里短信配置信息
  sms:
    accessKeyId: LTAIFCfcNOj1amZh
    accessKeySecret: YLXDCGqwn2GzzrQBjIcTRg1gIWDIk9
    signName: SaberCon # 签名名称
    templateCode: SMS_175480786 # 模板CODE
motto:
  user:
    default-avatar: https://motto.oss-cn-shenzhen.aliyuncs.com/user/avatar/takagi.jpg # 默认头像

