server:
  port: 80
  servlet:
    context-path: /api
logging:
  level:
    web: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/motto?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 开发时可以设置为更新，每次启动会更新数据库
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    database: 0 # Redis数据库索引（默认为0）
    password: # Redis服务器连接密码（默认为空）
aliyun:
  # OSS相关配置信息
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test # 访问身份验证中用到用户标识
    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: macro-oss # oss的存储空间
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    policy:
      expire: 300 # 签名有效期(S)
    dir:
      prefix: motto/images/ # 上传文件夹路径前缀
  # 阿里短信配置信息
  sms:
    accessKeyId: LTAIFCfcNOj1amZh
    accessKeySecret: YLXDCGqwn2GzzrQBjIcTRg1gIWDIk9
    signName: SaberCon # 签名名称
    templateCode: SMS_175480786 # 模板CODE
motto:
  user:
    defaultAvatar: https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png # 默认头像

